package homework.five.animals;

public class Demo {
	public static void main(String[] args) {

		Fish fish = new Fish();
		fish.move();
		fish.eat();
		fish.memory();
		fish.communicate();
		fish.swimming();

		System.out.println("---------------");

		Reptile reptile = new Reptile();
		reptile.move();
		reptile.eat();
		reptile.memory();
		reptile.communicate();

		System.out.println("---------------");

		Bird bird = new Bird();
		bird.move();
		bird.eat();
		bird.memory();
		bird.communicate();

		System.out.println("---------------");

		Mammal mammal = new Mammal();
		mammal.move();
		mammal.eat();
		mammal.memory();
		mammal.communicate();

		System.out.println("---------------");

		FlyingFish flyingFish = new FlyingFish();
		flyingFish.move();
		flyingFish.eat();
		flyingFish.memory();
		flyingFish.communicate();
		flyingFish.swimming();
		flyingFish.flying();

		System.out.println("---------------");

		SwimmingReptile floatingReptile = new SwimmingReptile();
		floatingReptile.move();
		floatingReptile.eat();
		floatingReptile.memory();
		floatingReptile.communicate();
		floatingReptile.swimming();

		System.out.println("---------------");

		FlyingBird flyingbird = new FlyingBird();
		flyingbird.move();
		flyingbird.eat();
		flyingbird.memory();
		flyingbird.communicate();
		flyingbird.flying();

		System.out.println("---------------");

		SwimmingBird swimmingbird = new SwimmingBird();
		swimmingbird.move();
		swimmingbird.eat();
		swimmingbird.memory();
		swimmingbird.communicate();
		swimmingbird.swimming();

		System.out.println("---------------");

		FlyingMammal flyingMammal = new FlyingMammal();
		flyingMammal.move();
		flyingMammal.eat();
		flyingMammal.memory();
		flyingMammal.communicate();
		flyingMammal.flying();

		System.out.println("---------------");

		SwimmingMammal swimmingMammal = new SwimmingMammal();
		swimmingMammal.move();
		swimmingMammal.eat();
		swimmingMammal.memory();
		swimmingMammal.communicate();
		swimmingMammal.swimming();

		// Fish moves...
		// Fish eats...
		// Memory of the fish...
		// Fish talks with other fish...
		// Fish swims...
		// ---------------
		// Reptile moves...
		// Reptile eats...
		// Memory reptile...
		// Reptile talks with other reptile...
		// ---------------
		// Bird moves...
		// Bird eats...
		// Memory bird...
		// Bird talks with other bird...
		// ---------------
		// Mammal moves...
		// Mammal eats...
		// Memory mammal...
		// Mammal talks with another mammal...
		// ---------------
		// Flying fish moves...
		// Flying fish eats...
		// Memory of flying fish...
		// Flying fish talking with another flying fish...
		// Flying fish swims...
		// Flying fish jumping over water...
		// ---------------
		// Swimming reptile moves...
		// Swimming reptile eats...
		// Memory swimming reptile...
		// Swimming reptile talks with another swimming reptile...
		// Swimming reptile swims...
		// ---------------
		// Flying bird moves...
		// Flying bird eats...
		// Memory flying bird...
		// Flying bird talks with another flying bird...
		// Flying bird flies...
		// ---------------
		// Swimming bird moves...
		// Swimming bird eats...
		// Memory swimming bird...
		// Swimming bird talks with another swimming bird...
		// Swimming bird swims...
		// ---------------
		// Flying mammal moves...
		// Flying mammal eats...
		// Memory flying mammal...
		// Flying mammal talks with another flying mammal...
		// Flying mammal flies...
		// ---------------
		// Swimming mammal moves...
		// Swimming mammal eats...
		// Memory swimming mammal...
		// Swimming mammal talks with another swimming mammal...
		// Swimming mammal swims...

	}
}
